### ISSUE TITLE
Biggest PR - dawah org, apps dev, islamic sites, forums,reddit, other religion sites,email etc

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/quran-api#17]
**Planning Phase**:

**Desgin:**
PR msg with askgod,qread, qvid
Target market for differnet categories-> devs, other layman/dawah org,  youtubers etc
differnetiation & positioning
Anyone should be able to use my source code, my website, my work, without any credits to me
begin msg with rqya of jibrl with intentn
different reading variant of quran in unicode (eg of indopak)
need help or any question please ask

**Task:**

- [x] Contact/Email collection (devs(g play, apple store) , dawah org, islamic,quran sites, yt reciation channels)(see toshare.txt , references.txt),Github (120mins) (taken: 130mins)
- [x] update each repo with how it works (60mins) (taken:10mins)
- [x] Msg designing with gfx,gif for each etc(hemingway,proaid) (90mins) (65miins taken)
- [x] spread (60mins)

**Possible Locations to spread:**

- [x] GitHub similar repos & git issues
- [x] reddit
- [x] ummah
- [x] email

Estimated time: 270mins
Time to complete with buffer: 350mins
